export const DishType = {
    Any: 'any',
    BiscuitsAndCookies: 'biscuits and cookies',
    Bread: 'bread',
    Cereals: 'cereals',
    CondimentsAndSauces: 'condiments and sauces',
    Desserts: 'desserts',
    Drinks: 'drinks',
    MainCourse: 'main course',
    Pancake: 'pancake',
    Preps: 'preps',
    Preserve: 'preserve',
    Salad: 'salad',
    Sandwiches: 'sandwiches',
    SideDish: 'side dish',
    Soup: 'soup',
    Starter: 'starter',
    Sweets: 'sweets',
};
